# Cloud Build pipeline for deploying to Cloud Run.
#
# Uses `gcloud run deploy --source .` which automatically:
#   - Builds the Docker image
#   - Creates an Artifact Registry repo
#   - Pushes the image
#   - Deploys to Cloud Run
#
# Prereqs:
# - Enable Cloud Run, Cloud Build, and Artifact Registry APIs
# - Create the secrets in Secret Manager (see substitutions below)
#
# Notes:
# - Vite variables are hardcoded in the Dockerfile as ARG defaults.
# - Server secrets (DB + Firebase Admin) are provided at runtime via Cloud Run.

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --source=.
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --set-secrets=DATABASE_URL_POOLER=$_DB_URL_SECRET:latest,DATABASE_URL=$_DB_URL_SECRET:latest,FIREBASE_SERVICE_ACCOUNT=$_FIREBASE_SA_SECRET:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE: mining-club
  _REGION: us-central1

  # Secret Manager secret NAMES (create these in your GCP project)
  _DB_URL_SECRET: neon_database_url
  _FIREBASE_SA_SECRET: firebase_service_account_json
