# Cloud Build pipeline for deploying to Cloud Run.
#
# Prereqs:
# - Enable Cloud Run + Cloud Build APIs
# - Create the secrets in Secret Manager (see substitutions below)
# - Create a Cloud Build trigger (or run manually) and override the _VITE_* substitutions
#
# Notes:
# - Vite variables (VITE_*) must be provided at *build time*.
# - Server secrets (DB + Firebase Admin) must be provided at *runtime* via Cloud Run.

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$BUILD_ID
      - --build-arg
      - VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID
      - --build-arg
      - VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN
      - --build-arg
      - VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$BUILD_ID

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$BUILD_ID
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - DATABASE_URL_POOLER=$_DB_URL_SECRET:latest,DATABASE_URL=$_DB_URL_SECRET:latest,FIREBASE_SERVICE_ACCOUNT=$_FIREBASE_SA_SECRET:latest

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$BUILD_ID

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE: mining-club
  _REGION: us-central1
  _REPO: cloud-run-source-deploy

  # Secret Manager secret NAMES (create these in your GCP project)
  # IMPORTANT: Do NOT put actual secret values (DB URLs, private keys) into this file.
  _DB_URL_SECRET: neon_database_url
  _FIREBASE_SA_SECRET: firebase_service_account_json

  # Build-time Vite variables (set these in your Cloud Build trigger)
  _VITE_FIREBASE_API_KEY: "REPLACE_ME"
  _VITE_FIREBASE_PROJECT_ID: "REPLACE_ME"
  _VITE_FIREBASE_APP_ID: "REPLACE_ME"
  _VITE_FIREBASE_AUTH_DOMAIN: "REPLACE_ME"
  _VITE_FIREBASE_STORAGE_BUCKET: "REPLACE_ME"
